[en]
  title = "Get Mockups"
  languageName = "English"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/en"

[id]
  title = "Get Mockups
  languageName = "English"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/id"
